FROM jenkins/jenkins:lts

USER root

# Install Docker CLI, make, g++, curl
RUN apt-get update && apt-get install -y \
    docker.io \
    make \
    g++ \
    curl \
    git \
    sudo \
    && apt-get clean

# Add Jenkins user to docker group so it can run Docker commands
RUN usermod -aG docker jenkins

USER jenkins
